Repository AY2324S2-CS2103T-W12-2/tp, pull requests merged in 2024-03, with the labels that each got.

#17 Update Aditya's Details
  docs/AboutUs.md
  docs/images/adityab4.png
  docs/team/adityab4.md
Labels: documentation

#28 Update website to remove references to AB3
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: documentation

#30 Add base module classes
  docs/AboutUs.md
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/module/Code.java
  src/main/java/seedu/address/model/module/Description.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/Title.java
Labels: type.Chore, priority.High

#56 Update DG content to reflect updates better
  .gitignore
  docs/DeveloperGuide.md
Labels: documentation, type.Chore, priority.Medium
